PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ssn: <https://www.w3.org/ns/ssn/>

SELECT ?sensorId ?sensorLabel
WHERE {
	<OBS_ID> rdf:type ssn:Platform .
    <OBS_ID> ssn:attachedSystem ?sensorId .
    ?sensorId rdfs:label ?sensorLabel .
}