PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ssn: <https://www.w3.org/ns/ssn/>
PREFIX schema: <http://schema.org/>
PREFIX unit: <http://qudt.org/vocab/unit#>

SELECT ?sensor ?observatory ?rangeValue ?rangeUnit ?frequencyValue ?frequencyUnit
WHERE {
[ 
  rdf:type ssn:SensingDevice ;
  rdfs:label ?sensor ;
  ssn:onPlatform [
    rdfs:label ?observatory      
  ] ;
  ssn:hasMeasurementCapability [
    ssn:hasMeasurementProperty [
      rdf:type ssn:MeasurementRange ;
      schema:value ?rangeValue ;
      schema:unitCode ?rangeUnit ;
    ]
  ] ;
  ssn:hasMeasurementCapability [
    ssn:hasMeasurementProperty [
      rdf:type ssn:MeasurementFrequency ;
      schema:value ?frequencyValue ;
      schema:unitCode ?frequencyUnit ;
    ]
  ]
]
}

